Added some echos and comment
To automate the update all comments and the more line need to be disabled.

diff --git a/update b/update
--- a/update
+++ b/update
@@ -4,15 +4,21 @@
 #
 # You MUST edit the YourHomeDir variable below in the three places, and maybe also the actual gamadv-xtd3 dir.
 # The reason for hardcoding the program dir is because you can have several separate GAM versions installed at the same time, and may not want to update them all.
+# Comment *all* echo lines and the more line if you are scheduling an automatic update.
+
+echo
+echo "Checking to see if there is an update of GAMADV-XTD3."
+echo
 
 if /home/YourHomeDir/gamadv-xtd3/gam version checkrc; then
-        echo $? #This line isn't necessary. I have it just to see the error code from the checkrc command. 0 means TRUE and that the versions match.
+        echo $? # This line isn't necessary. I have it just to see the error code from the checkrc command. 0 means TRUE and that the versions match.
         echo "You are using the current version!"
         exit
 else
-        echo $? #This line isn't necessary. Just like the one above.
+        echo $? # This line isn't necessary. Just like the one above.
         echo "There's a newer version of GAMADV-XTD3. Downloading it now."
         bash <(curl -s -S -L https://git.io/fhZWP) -l -d /home/YourHomeDir
+        wait
         more /home/YourHomeDir/gamadv-xtd3/GamUpdate.txt #This line opens the GamUpdate.txt file, so I can see what new features or bugfixes has been added.
-        #If you are to fully automate the updating, you need to disable this line completely.
+        # If you are to fully automate the updating, you need to disable the line above completely.
 fi
